service: auth-server

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-1
  timeout: 30 #optional,in seconds, default 6
  environment:
    #access secrets from config.json file in same folder
    CLIENT_ID: ${file(config.json):CLIENT_ID}
    CLIENT_SECRET: ${file(config.json):CLIENT_SECRET}
    CALENDAR_ID: ${file(config.json):CALENDAR_ID}

functions:
  getAuthURL:
    handler: handler.getAuthURL
    events:
      - http:
          path: api/get-auth-url
          method: get
  getAccessToken:
    handler: handler.getAccessToken
    events:
      - http:
          path: api/token/{code} #{code}=auth code received when user authorizes Meet app
          method: get
  getCalendarEvents:
    handler: handler.getCalendarEvents
    events:
      - http:
          path: api/get-events/{access_token} #references getAccessToken()
          method: get